# Generated by Django 5.2.8 on 2025-12-04 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waf_core', '0004_tenant_domain_verified_tenant_verification_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoBlockEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('block', 'Blocked'), ('allow', 'Allowed'), ('challenge', 'Challenged')], default='block', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geo_block_events', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'Geo-Block Event',
                'verbose_name_plural': 'Geo-Block Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='waf_securit_tenant__515f3f_idx'), models.Index(fields=['country_code', 'timestamp'], name='waf_securit_country_3e5c0c_idx'), models.Index(fields=['action', 'timestamp'], name='waf_securit_action_af9c1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPReputationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('reputation_score', models.IntegerField(default=0, help_text='Reputation score 0-100 (higher = more malicious)')),
                ('reputation_level', models.CharField(choices=[('excellent', 'Excellent (0-20)'), ('good', 'Good (21-40)'), ('neutral', 'Neutral (41-60)'), ('suspicious', 'Suspicious (61-80)'), ('malicious', 'Malicious (81-100)')], default='neutral', max_length=20)),
                ('total_violations', models.IntegerField(default=0)),
                ('sql_injection_attempts', models.IntegerField(default=0)),
                ('xss_attempts', models.IntegerField(default=0)),
                ('rate_limit_violations', models.IntegerField(default=0)),
                ('bot_detections', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('auto_blocked', models.BooleanField(default=False, help_text='Automatically blocked by reputation system')),
                ('block_reason', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_violation', models.DateTimeField(blank=True, null=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_decay', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_reputations', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'IP Reputation Score',
                'verbose_name_plural': 'IP Reputation Scores',
                'ordering': ['-reputation_score', '-last_seen'],
                'indexes': [models.Index(fields=['tenant', 'ip_address'], name='waf_securit_tenant__883570_idx'), models.Index(fields=['tenant', 'reputation_score'], name='waf_securit_tenant__0b7bc2_idx'), models.Index(fields=['is_blocked'], name='waf_securit_is_bloc_73ef9e_idx')],
                'unique_together': {('tenant', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='RateLimitViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('user_agent', models.TextField(blank=True)),
                ('limit_type', models.CharField(choices=[('per_minute', 'Per Minute'), ('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_ip_minute', 'Per IP Per Minute'), ('per_ip_hour', 'Per IP Per Hour')], max_length=20)),
                ('limit_value', models.IntegerField(help_text='The rate limit threshold')),
                ('current_count', models.IntegerField(help_text='Current request count when violated')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_violations', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'Rate Limit Violation',
                'verbose_name_plural': 'Rate Limit Violations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='waf_securit_tenant__aad1cf_idx'), models.Index(fields=['ip_address', 'timestamp'], name='waf_securit_ip_addr_4ed6c1_idx'), models.Index(fields=['limit_type', 'timestamp'], name='waf_securit_limit_t_0eff2a_idx')],
            },
        ),
    ]
