# Generated by Django 5.2.8 on 2025-11-28 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waf_core', '0002_alter_firewallrule_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_name', models.CharField(max_length=200)),
                ('suggested_pattern', models.TextField(help_text='Regex pattern for the rule')),
                ('rule_type', models.CharField(choices=[('sql_injection', 'SQL Injection Protection'), ('xss', 'Cross-Site Scripting (XSS) Protection'), ('bot_protection', 'Bot Protection'), ('rate_limiting', 'Rate Limiting'), ('geo_blocking', 'Geographic Blocking'), ('ip_whitelist', 'IP Whitelist'), ('ip_blacklist', 'IP Blacklist'), ('custom', 'Custom Rule')], max_length=50)),
                ('suggested_action', models.CharField(choices=[('block', 'Block Request'), ('allow', 'Allow Request'), ('log', 'Log Only'), ('challenge', 'Challenge (Captcha)'), ('rate_limit', 'Rate Limit')], default='block', max_length=20)),
                ('suggested_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence_score', models.FloatField(help_text='ML confidence in this rule (0-1)')),
                ('supporting_events', models.JSONField(default=list, help_text='Security event IDs that support this rule')),
                ('attack_count', models.IntegerField(default=0, help_text='Number of attacks this would have blocked')),
                ('pattern_frequency', models.IntegerField(default=0, help_text='How often this pattern appears')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_approved', 'Auto-Approved')], default='pending', max_length=20)),
                ('created_by_ml', models.BooleanField(default=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_adaptive_rule', to='waf_core.firewallrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_rules', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'Adaptive Rule',
                'verbose_name_plural': 'Adaptive Rules',
                'ordering': ['-confidence_score', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='waf_ml_adap_tenant__e7a187_idx'), models.Index(fields=['confidence_score'], name='waf_ml_adap_confide_16db08_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_signature', models.CharField(help_text='Hash of request characteristics', max_length=64)),
                ('source_ip', models.GenericIPAddressField()),
                ('request_path', models.CharField(max_length=500)),
                ('request_method', models.CharField(max_length=10)),
                ('anomaly_score', models.FloatField(help_text='Anomaly score from ML model (0-1, higher = more anomalous)')),
                ('is_anomaly', models.BooleanField(default=False, help_text='Score exceeded threshold')),
                ('features', models.JSONField(default=dict, help_text='Extracted features for this request')),
                ('was_blocked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blocking_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomaly_blocks', to='waf_core.firewallrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_scores', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'Anomaly Score',
                'verbose_name_plural': 'Anomaly Scores',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='waf_ml_anom_tenant__a69a1b_idx'), models.Index(fields=['anomaly_score'], name='waf_ml_anom_anomaly_42abdf_idx'), models.Index(fields=['is_anomaly', 'timestamp'], name='waf_ml_anom_is_anom_b42b01_idx')],
            },
        ),
        migrations.CreateModel(
            name='FalsePositiveFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_false_positive', models.BooleanField(default=True)),
                ('user_comment', models.TextField(blank=True)),
                ('reported_by', models.CharField(help_text='User who reported this', max_length=100)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_action', models.CharField(blank=True, help_text='Action taken to resolve', max_length=200)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='waf_core.securityevent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_positive_feedback', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'False Positive Feedback',
                'verbose_name_plural': 'False Positive Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'resolved'], name='waf_ml_fals_tenant__c61e27_idx'), models.Index(fields=['security_event'], name='waf_ml_fals_securit_3c946f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('anomaly_detector', 'Anomaly Detector'), ('rule_suggester', 'Rule Suggester'), ('pattern_classifier', 'Pattern Classifier')], max_length=50)),
                ('model_version', models.IntegerField(default=1)),
                ('model_data', models.BinaryField(help_text='Serialized model using joblib')),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('precision_score', models.FloatField(default=0.0)),
                ('recall_score', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('training_samples_count', models.IntegerField(default=0)),
                ('training_duration_seconds', models.FloatField(default=0.0)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('training_config', models.JSONField(default=dict, help_text='Hyperparameters and config')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['tenant', 'model_type', 'is_active'], name='waf_ml_mlmo_tenant__b52382_idx')],
                'unique_together': {('tenant', 'model_type', 'model_version')},
            },
        ),
        migrations.CreateModel(
            name='RuleLearningHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('true_positives', models.IntegerField(default=0, help_text='Correctly blocked attacks')),
                ('false_positives', models.IntegerField(default=0, help_text='Incorrectly blocked legitimate requests')),
                ('true_negatives', models.IntegerField(default=0, help_text='Correctly allowed legitimate requests')),
                ('false_negatives', models.IntegerField(default=0, help_text='Missed attacks')),
                ('confidence_score', models.FloatField(default=0.5, help_text='Overall rule confidence (0-1)')),
                ('precision', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('f1_score', models.FloatField(default=0.0)),
                ('evaluation_period_start', models.DateTimeField()),
                ('evaluation_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_history', to='waf_core.firewallrule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_histories', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'Rule Learning History',
                'verbose_name_plural': 'Rule Learning Histories',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['rule', 'tenant'], name='waf_ml_rule_rule_id_afbc54_idx'), models.Index(fields=['tenant', 'confidence_score'], name='waf_ml_rule_tenant__b453c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('window_duration_minutes', models.IntegerField(default=60)),
                ('request_count', models.IntegerField(default=0)),
                ('unique_ips', models.IntegerField(default=0)),
                ('avg_request_size', models.FloatField(default=0.0)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('common_paths', models.JSONField(default=list, help_text='Most frequently accessed paths')),
                ('common_user_agents', models.JSONField(default=list, help_text='Most common user agents')),
                ('common_methods', models.JSONField(default=dict, help_text='HTTP method distribution')),
                ('avg_path_depth', models.FloatField(default=0.0)),
                ('avg_param_count', models.FloatField(default=0.0)),
                ('avg_header_count', models.FloatField(default=0.0)),
                ('avg_entropy', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_patterns', to='waf_core.tenant')),
            ],
            options={
                'verbose_name': 'Traffic Pattern',
                'verbose_name_plural': 'Traffic Patterns',
                'ordering': ['-time_window_start'],
                'indexes': [models.Index(fields=['tenant', 'time_window_start'], name='waf_ml_traf_tenant__d6e87f_idx')],
            },
        ),
    ]
