# Generated by Django 5.2.6 on 2025-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_ip",
                    models.GenericIPAddressField(
                        help_text="The source IP address of the request."
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SQLI", "SQL Injection"),
                            ("XSS", "Cross-Site Scripting"),
                            ("LFI", "Local File Inclusion"),
                            ("RCE", "Remote Code Execution"),
                            ("OTHER", "Other"),
                        ],
                        help_text="The type of security event.",
                        max_length=10,
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        help_text="The name of the rule that was triggered.",
                        max_length=255,
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("BLOCKED", "Blocked"),
                            ("LOGGED", "Logged"),
                            ("ALLOWED", "Allowed"),
                        ],
                        help_text="The action taken by the WAF.",
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        help_text="Detailed information about the request."
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
