# Generated by Django 5.2.6 on 2025-09-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waf_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firewallrule",
            name="pattern",
            field=models.TextField(
                blank=True, help_text="Regex pattern or rule definition"
            ),
        ),
    ]
