# Generated by Django 5.2.8 on 2025-12-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_core', '0002_alter_firewallrule_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='origin_url',
            field=models.URLField(blank=True, help_text='Origin backend URL for this tenant (e.g., https://app.tenant.com)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='waf_host',
            field=models.CharField(blank=True, help_text='Subdomain on the WAF (e.g., tenant1.waf-app.site)', max_length=255, null=True, unique=True),
        ),
    ]
