# Generated by Django 5.2.8 on 2025-12-02 04:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf_core', '0003_tenant_origin_url_tenant_waf_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='domain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='verification_method',
            field=models.CharField(choices=[('dns', 'DNS TXT Record'), ('file', 'File Upload')], default='dns', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
