# Generated by Django 5.2.6 on 2025-09-09 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WAFRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for the rule.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="The regex pattern to match against.", max_length=255
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Block Request"),
                            ("LOG", "Log Only"),
                            ("REDIRECT", "Redirect Request"),
                        ],
                        default="BLOCK",
                        help_text="The action to take when the pattern is matched.",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the rule is currently active."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
