"""
Django settings for waf_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "waf_project.waf_core",
    "waf_project.waf_engine",
    "waf_project.waf_ml",
    "waf_project.waf_security",  # Advanced security features
    "rest_framework",
    "rest_framework.authtoken",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "waf_project.waf_engine.tenant_middleware.TenantMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "waf_project.waf_engine.middleware.WAFMiddleware"
]

ROOT_URLCONF = "waf_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "waf_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = '/admin/login/'

AUTH_USER_MODEL = "waf_core.User"


LOGIN_REDIRECT_URL = 'dashboard'   # Redirect after successful login
LOGOUT_REDIRECT_URL = 'login'      # Redirect after logout

GEOIP_PATH = BASE_DIR / 'waf_project' / 'geoip'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# WAF Machine Learning Configuration
WAF_ML_ENABLED = False
WAF_ML_ANOMALY_THRESHOLD = 0.8  # Score above this triggers alerts
WAF_ML_AUTO_APPROVE_THRESHOLD = 0.95  # Auto-approve rules above this confidence
WAF_ML_TRAINING_WINDOW_DAYS = 7  # Days of data for training
WAF_ML_MIN_SAMPLES_FOR_TRAINING = 100  # Minimum requests before training
WAF_ML_FEATURE_EXTRACTION_ENABLED = True
WAF_ML_PATTERN_AGGREGATION_MINUTES = 60  # Aggregate traffic patterns every hour
WAF_ML_ENABLE_FALLBACK_RULES = False  # Set to True to enable automatic fallback rule generation

# Nginx Configuration Automation
NGINX_CONFIG_PATH = os.getenv('NGINX_CONFIG_PATH', '/etc/nginx/nginx.conf')
NGINX_TEMPLATE_DIR = os.path.join(BASE_DIR, 'waf_project', 'waf_core', 'templates', 'nginx')
NGINX_RELOAD_COMMAND = os.getenv('NGINX_RELOAD_COMMAND', 'docker exec nginx nginx -s reload')
NGINX_TEST_COMMAND = os.getenv('NGINX_TEST_COMMAND', 'docker exec nginx nginx -t')
NGINX_AUTO_RELOAD = os.getenv('NGINX_AUTO_RELOAD', 'True').lower() == 'true'

# ============================================================================
# WAF Advanced Security Features
# ============================================================================

# Feature Flags - Enable/disable specific security features
WAF_ENABLE_RATE_LIMITING = True  # Per-tenant rate limiting
WAF_ENABLE_IP_REPUTATION = True  # IP reputation tracking and auto-blocking
WAF_ENABLE_RULE_CACHING = True   # Cache WAF rules for performance
WAF_ENABLE_GEOIP_CACHING = True  # Cache GeoIP lookups

# IP Reputation Configuration
WAF_IP_REPUTATION_BLOCK_THRESHOLD = 80  # Auto-block IPs with score >= this value (0-100)
WAF_IP_REPUTATION_DECAY_RATE = 5  # Points to decay per interval
WAF_IP_REPUTATION_DECAY_INTERVAL = 24  # Hours between decay applications

# GeoIP Configuration
WAF_GEOIP_CACHE_TTL = 3600  # Cache IP-to-country lookups for 1 hour (seconds)
WAF_GEOIP_ALLOW_UNKNOWN = True  # Allow requests when country can't be determined

# Cache Configuration
# For production, configure Redis or Memcached for better performance
# Development uses in-memory cache by default
#
# Example Redis configuration:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'KEY_PREFIX': 'waf',
#         'TIMEOUT': 300,  # 5 minutes default
#     }
# }


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'waf_engine': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'waf_core': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'waf_security': {  # Advanced security features
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
